package plugintest

import (
	"fmt"
	"strings"
	"sync"

	plugin "github.com/paca/plugin-sdk"
)

// ── InMemoryDB ────────────────────────────────────────────────────────────────

// table is an in-memory table of rows.
type table struct {
	columns []string
	rows    [][]any
}

// InMemoryDB is a simple in-memory SQL backend for testing.
// It supports SELECT, INSERT, UPDATE, DELETE against pre-seeded tables.
// The query parsing is intentionally minimal — it supports the parameterised
// patterns typically generated by plugin code ($1, $2, …).
type InMemoryDB struct {
	mu     sync.Mutex
	tables map[string]*table
}

func newInMemoryDB() *InMemoryDB {
	return &InMemoryDB{tables: make(map[string]*table)}
}

// SeedRows loads initial data for the named table.  Subsequent calls replace
// the previous seed entirely.
func (db *InMemoryDB) SeedRows(tableName string, columns []string, rows [][]any) {
	db.mu.Lock()
	defer db.mu.Unlock()
	copied := make([][]any, len(rows))
	for i, row := range rows {
		r := make([]any, len(row))
		copy(r, row)
		copied[i] = r
	}
	db.tables[strings.ToLower(tableName)] = &table{columns: columns, rows: copied}
}

// AllRows returns a copy of all rows in a table.  Useful for asserting state
// after a mutation.
func (db *InMemoryDB) AllRows(tableName string) [][]any {
	db.mu.Lock()
	defer db.mu.Unlock()
	t, ok := db.tables[strings.ToLower(tableName)]
	if !ok {
		return nil
	}
	out := make([][]any, len(t.rows))
	for i, row := range t.rows {
		r := make([]any, len(row))
		copy(r, row)
		out[i] = r
	}
	return out
}

// Query implements plugin.DBBackend.
// Supports:
//   - SELECT * FROM <table>
//   - SELECT <cols> FROM <table> WHERE <col> = $N
func (db *InMemoryDB) Query(sql string, params []any) (*plugin.DBQueryResult, error) {
	db.mu.Lock()
	defer db.mu.Unlock()

	upper := strings.TrimSpace(strings.ToUpper(sql))
	switch {
	case strings.HasPrefix(upper, "SELECT"):
		return db.querySelect(sql, params)
	case strings.HasPrefix(upper, "INSERT"):
		return db.queryInsert(sql, params)
	default:
		return nil, fmt.Errorf("InMemoryDB.Query: only SELECT and INSERT ... RETURNING are supported (got %q)", sql)
	}

}

func (db *InMemoryDB) querySelect(sql string, params []any) (*plugin.DBQueryResult, error) {
	tableName, whereCol, whereParam, err := parseSimpleSelect(sql)
	if err != nil {
		return nil, err
	}
	t, ok := db.tables[strings.ToLower(tableName)]
	if !ok {
		return &plugin.DBQueryResult{}, nil
	}

	result := &plugin.DBQueryResult{Columns: t.columns}
	colIdx := colIndex(t.columns, whereCol)

	for _, row := range t.rows {
		if whereCol == "" || (colIdx >= 0 && colIdx < len(row) && fmt.Sprint(row[colIdx]) == fmt.Sprint(params[whereParam-1])) {
			rowCopy := make([]any, len(row))
			copy(rowCopy, row)
			result.Rows = append(result.Rows, rowCopy)
		}
	}
	return result, nil
}

func (db *InMemoryDB) queryInsert(sql string, params []any) (*plugin.DBQueryResult, error) {
	returningCols, err := parseReturningColumns(sql)
	if err != nil {
		return nil, err
	}
	if len(returningCols) == 0 {
		return nil, fmt.Errorf("InMemoryDB.Query: INSERT queries must include RETURNING (got %q)", sql)
	}

	t, row, err := db.insertRow(sql, params)
	if err != nil {
		return nil, err
	}

	result := &plugin.DBQueryResult{Columns: returningCols, Rows: [][]any{{}}}
	for _, col := range returningCols {
		colIdx := colIndex(t.columns, col)
		if colIdx < 0 || colIdx >= len(row) {
			return nil, fmt.Errorf("InMemoryDB.queryInsert: column %q not found in table %q", col, parseInsertTableName(sql))
		}
		result.Rows[0] = append(result.Rows[0], row[colIdx])
	}
	return result, nil
}

// Exec implements plugin.DBBackend.
// Supports INSERT INTO <table> VALUES (...) and DELETE FROM <table> WHERE <col> = $N.
func (db *InMemoryDB) Exec(sql string, params []any) (int64, error) {
	db.mu.Lock()
	defer db.mu.Unlock()

	upper := strings.TrimSpace(strings.ToUpper(sql))
	switch {
	case strings.HasPrefix(upper, "INSERT"):
		return db.execInsert(sql, params)
	case strings.HasPrefix(upper, "UPDATE"):
		return db.execUpdate(sql, params)
	case strings.HasPrefix(upper, "DELETE"):
		return db.execDelete(sql, params)
	default:
		return 0, fmt.Errorf("InMemoryDB.Exec: unsupported statement %q", sql)
	}
}

func (db *InMemoryDB) execInsert(sql string, params []any) (int64, error) {
	_, _, err := db.insertRow(sql, params)
	if err != nil {
		return 0, err
	}
	return 1, nil
}

func (db *InMemoryDB) insertRow(sql string, params []any) (*table, []any, error) {
	tableName, insertCols, err := parseInsertColumns(sql)
	if err != nil {
		return nil, nil, err
	}
	t, ok := db.tables[strings.ToLower(tableName)]
	if !ok {
		return nil, nil, fmt.Errorf("InMemoryDB: table %q not found", tableName)
	}

	row := make([]any, len(t.columns))
	if len(insertCols) == 0 {
		if len(params) != len(t.columns) {
			return nil, nil, fmt.Errorf("InMemoryDB.insertRow: expected %d params for table %q, got %d", len(t.columns), tableName, len(params))
		}
		copy(row, params)
	} else {
		if len(params) != len(insertCols) {
			return nil, nil, fmt.Errorf("InMemoryDB.insertRow: expected %d params for table %q, got %d", len(insertCols), tableName, len(params))
		}
		for i, col := range insertCols {
			colIdx := colIndex(t.columns, col)
			if colIdx < 0 {
				return nil, nil, fmt.Errorf("InMemoryDB.insertRow: column %q not found in table %q", col, tableName)
			}
			row[colIdx] = params[i]
		}
	}

	idIdx := colIndex(t.columns, "id")
	if idIdx >= 0 && row[idIdx] == nil {
		row[idIdx] = fmt.Sprintf("generated-id-%d", len(t.rows)+1)
	}

	t.rows = append(t.rows, row)
	return t, row, nil
}

func (db *InMemoryDB) execDelete(sql string, params []any) (int64, error) {
	tableName, whereCol, whereParam, err := parseSimpleWhere(sql)
	if err != nil {
		return 0, err
	}
	t, ok := db.tables[strings.ToLower(tableName)]
	if !ok {
		return 0, nil
	}
	if whereCol == "" {
		count := int64(len(t.rows))
		t.rows = nil
		return count, nil
	}
	colIdx := colIndex(t.columns, whereCol)
	var kept [][]any
	var deleted int64
	for _, row := range t.rows {
		if colIdx >= 0 && colIdx < len(row) && fmt.Sprint(row[colIdx]) == fmt.Sprint(params[whereParam-1]) {
			deleted++
		} else {
			kept = append(kept, row)
		}
	}
	t.rows = kept
	return deleted, nil
}

func (db *InMemoryDB) execUpdate(sql string, params []any) (int64, error) {
	tableName, assignments, conditions, err := parseSimpleUpdate(sql)
	if err != nil {
		return 0, err
	}

	t, ok := db.tables[strings.ToLower(tableName)]
	if !ok {
		return 0, nil
	}

	updated := int64(0)
	for _, row := range t.rows {
		matches, matchErr := rowMatchesConditions(t.columns, row, conditions, params)
		if matchErr != nil {
			return 0, matchErr
		}
		if !matches {
			continue
		}
		for _, assignment := range assignments {
			colIdx := colIndex(t.columns, assignment.column)
			if colIdx < 0 || colIdx >= len(row) {
				return 0, fmt.Errorf("InMemoryDB.execUpdate: column %q not found in table %q", assignment.column, tableName)
			}
			row[colIdx] = params[assignment.paramIdx-1]
		}
		updated++
	}

	return updated, nil
}

// ── Simple SQL parser helpers ─────────────────────────────────────────────────

type colParam struct {
	column   string
	paramIdx int
}

// parseSimpleSelect extracts table name and optional WHERE col = $N.
// Only supports: SELECT ... FROM <table> [WHERE <col> = $N]
func parseSimpleSelect(sql string) (table, whereCol string, whereParam int, err error) {
	upper := strings.ToUpper(sql)
	fromIdx := strings.Index(upper, " FROM ")
	if fromIdx < 0 {
		return "", "", 0, fmt.Errorf("parseSimpleSelect: no FROM in %q", sql)
	}
	rest := strings.TrimSpace(sql[fromIdx+6:])
	whereIdx := strings.Index(strings.ToUpper(rest), " WHERE ")
	if whereIdx < 0 {
		return strings.Fields(rest)[0], "", 0, nil
	}
	table = strings.Fields(rest[:whereIdx])[0]
	wherePart := strings.TrimSpace(rest[whereIdx+7:])
	col, param, e := parseColParam(wherePart)
	return table, col, param, e
}

// parseSimpleWhere extracts table name and WHERE condition for DELETE.
func parseSimpleWhere(sql string) (tableName, whereCol string, whereParam int, err error) {
	upper := strings.ToUpper(sql)
	// DELETE FROM <table> WHERE <col> = $N
	fromIdx := strings.Index(upper, " FROM ")
	if fromIdx < 0 {
		return "", "", 0, fmt.Errorf("parseSimpleWhere: no FROM in %q", sql)
	}
	rest := strings.TrimSpace(sql[fromIdx+6:])
	whereIdx := strings.Index(strings.ToUpper(rest), " WHERE ")
	if whereIdx < 0 {
		return strings.Fields(rest)[0], "", 0, nil
	}
	tableName = strings.Fields(rest[:whereIdx])[0]
	wherePart := strings.TrimSpace(rest[whereIdx+7:])
	col, wp, e := parseColParam(wherePart)
	return tableName, col, wp, e
}

// parseSimpleUpdate extracts the table name, SET assignments, and WHERE conditions.
// Only supports: UPDATE <table> SET <col> = $N[, <col> = $N ...] WHERE <col> = $N [AND <col> = $N ...]
func parseSimpleUpdate(sql string) (tableName string, assignments []colParam, conditions []colParam, err error) {
	trimmed := strings.TrimSpace(sql)
	upper := strings.ToUpper(trimmed)
	if !strings.HasPrefix(upper, "UPDATE ") {
		return "", nil, nil, fmt.Errorf("parseSimpleUpdate: no UPDATE in %q", sql)
	}

	setIdx := strings.Index(upper, " SET ")
	if setIdx < 0 {
		return "", nil, nil, fmt.Errorf("parseSimpleUpdate: no SET in %q", sql)
	}
	whereIdx := strings.Index(upper, " WHERE ")
	if whereIdx < 0 {
		return "", nil, nil, fmt.Errorf("parseSimpleUpdate: no WHERE in %q", sql)
	}

	tableName = strings.TrimSpace(trimmed[len("UPDATE "):setIdx])
	assignments, err = parseAssignments(trimmed[setIdx+5 : whereIdx])
	if err != nil {
		return "", nil, nil, err
	}
	conditions, err = parseConditions(trimmed[whereIdx+7:])
	if err != nil {
		return "", nil, nil, err
	}
	return tableName, assignments, conditions, nil
}

func parseAssignments(s string) ([]colParam, error) {
	parts := strings.Split(s, ",")
	assignments := make([]colParam, 0, len(parts))
	for _, part := range parts {
		col, paramIdx, err := parseColParam(strings.TrimSpace(part))
		if err != nil {
			return nil, err
		}
		assignments = append(assignments, colParam{column: col, paramIdx: paramIdx})
	}
	return assignments, nil
}

func parseConditions(s string) ([]colParam, error) {
	parts := strings.Split(s, "AND")
	conditions := make([]colParam, 0, len(parts))
	for _, part := range parts {
		col, paramIdx, err := parseColParam(strings.TrimSpace(part))
		if err != nil {
			return nil, err
		}
		conditions = append(conditions, colParam{column: col, paramIdx: paramIdx})
	}
	return conditions, nil
}

func rowMatchesConditions(columns []string, row []any, conditions []colParam, params []any) (bool, error) {
	for _, condition := range conditions {
		colIdx := colIndex(columns, condition.column)
		if colIdx < 0 || colIdx >= len(row) {
			return false, fmt.Errorf("rowMatchesConditions: column %q not found", condition.column)
		}
		if condition.paramIdx <= 0 || condition.paramIdx > len(params) {
			return false, fmt.Errorf("rowMatchesConditions: param index %d out of range", condition.paramIdx)
		}
		if fmt.Sprint(row[colIdx]) != fmt.Sprint(params[condition.paramIdx-1]) {
			return false, nil
		}
	}
	return true, nil
}

// parseColParam parses "<col> = $N" into col name and param index (1-based).
func parseColParam(s string) (col string, paramIdx int, err error) {
	parts := strings.Fields(s)
	if len(parts) < 3 {
		return "", 0, fmt.Errorf("parseColParam: unexpected %q", s)
	}
	col = parts[0]
	paramStr := parts[2]
	if !strings.HasPrefix(paramStr, "$") {
		return "", 0, fmt.Errorf("parseColParam: expected $N, got %q", paramStr)
	}
	var idx int
	if _, e := fmt.Sscanf(paramStr[1:], "%d", &idx); e != nil {
		return "", 0, e
	}
	return col, idx, nil
}

// parseInsertTable extracts the table name from INSERT INTO <table> ...
func parseInsertTable(sql string) (string, error) {
	tableName, _, err := parseInsertColumns(sql)
	return tableName, err
}

func parseInsertTableName(sql string) string {
	tableName, _ := parseInsertTable(sql)
	return tableName
}

func parseInsertColumns(sql string) (tableName string, columns []string, err error) {
	upper := strings.ToUpper(sql)
	intoIdx := strings.Index(upper, " INTO ")
	if intoIdx < 0 {
		return "", nil, fmt.Errorf("parseInsertColumns: no INTO in %q", sql)
	}
	rest := strings.TrimSpace(sql[intoIdx+6:])
	openIdx := strings.Index(rest, "(")
	if openIdx < 0 {
		return strings.Fields(rest)[0], nil, nil
	}
	tableName = strings.TrimSpace(rest[:openIdx])
	closeIdx := strings.Index(rest[openIdx:], ")")
	if closeIdx < 0 {
		return "", nil, fmt.Errorf("parseInsertColumns: no closing ')' in %q", sql)
	}
	columnList := rest[openIdx+1 : openIdx+closeIdx]
	for _, col := range strings.Split(columnList, ",") {
		trimmed := strings.TrimSpace(col)
		if trimmed != "" {
			columns = append(columns, trimmed)
		}
	}
	return tableName, columns, nil
}

func parseReturningColumns(sql string) ([]string, error) {
	upper := strings.ToUpper(sql)
	returningIdx := strings.Index(upper, " RETURNING ")
	if returningIdx < 0 {
		return nil, nil
	}
	colsPart := strings.TrimSpace(sql[returningIdx+11:])
	if colsPart == "" {
		return nil, fmt.Errorf("parseReturningColumns: missing RETURNING columns in %q", sql)
	}
	var cols []string
	for _, col := range strings.Split(colsPart, ",") {
		trimmed := strings.TrimSpace(col)
		if trimmed != "" {
			cols = append(cols, trimmed)
		}
	}
	return cols, nil
}

func colIndex(columns []string, col string) int {
	if col == "" {
		return -1
	}
	lower := strings.ToLower(col)
	for i, c := range columns {
		if strings.ToLower(c) == lower {
			return i
		}
	}
	return -1
}

// ── InMemoryKV ────────────────────────────────────────────────────────────────

// InMemoryKV is a simple map-backed key-value store.
type InMemoryKV struct {
	mu   sync.Mutex
	data map[string]string
}

func newInMemoryKV() *InMemoryKV {
	return &InMemoryKV{data: make(map[string]string)}
}

func (k *InMemoryKV) Get(key string) (string, bool) {
	k.mu.Lock()
	defer k.mu.Unlock()
	v, ok := k.data[key]
	return v, ok
}

func (k *InMemoryKV) Set(key, value string) {
	k.mu.Lock()
	defer k.mu.Unlock()
	k.data[key] = value
}

func (k *InMemoryKV) Delete(key string) {
	k.mu.Lock()
	defer k.mu.Unlock()
	delete(k.data, key)
}

// ── CapturingLogger ───────────────────────────────────────────────────────────

// LogEntry is a single captured log message.
type LogEntry struct {
	Level int
	Msg   string
}

// CapturingLogger records log messages so tests can assert on them.
type CapturingLogger struct {
	mu      sync.Mutex
	entries []LogEntry
}

func newCapturingLogger() *CapturingLogger { return &CapturingLogger{} }

func (l *CapturingLogger) Log(level int, msg string) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.entries = append(l.entries, LogEntry{level, msg})
}

// Entries returns a copy of all captured log entries.
func (l *CapturingLogger) Entries() []LogEntry {
	l.mu.Lock()
	defer l.mu.Unlock()
	out := make([]LogEntry, len(l.entries))
	copy(out, l.entries)
	return out
}

// HasMessage returns true if any entry contains the given substring.
func (l *CapturingLogger) HasMessage(substr string) bool {
	l.mu.Lock()
	defer l.mu.Unlock()
	for _, e := range l.entries {
		if strings.Contains(e.Msg, substr) {
			return true
		}
	}
	return false
}

// ── InMemoryConfig ────────────────────────────────────────────────────────────

// InMemoryConfig provides a simple map-backed config store.
type InMemoryConfig struct {
	mu   sync.Mutex
	data map[string]string
}

func newInMemoryConfig() *InMemoryConfig {
	return &InMemoryConfig{data: make(map[string]string)}
}

// Set stores a config value.
func (c *InMemoryConfig) Set(key, value string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.data[key] = value
}

func (c *InMemoryConfig) Get(key string) (string, bool) {
	c.mu.Lock()
	defer c.mu.Unlock()
	v, ok := c.data[key]
	return v, ok
}
